name: Integracion y Versionado

on:
  pull_request:
    branches:
      - Rama-QA

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '4.8.x'

      - name: Install NuGet dependencies
        run: nuget restore

      - name: Build solution
        run: msbuild PracticandoPersonas.sln /p:Configuration=Release

      - name: Run tests
        run: |
          vstest.console.exe **\*Tests.dll --logger:trx
